language: python
python:
  - "3.4"
  # - "3.5"
  # - "3.6"
  # - "nightly" # currently points to 3.7-dev

env:
  - DJANGO_SETTINGS_MODULE=dri.settings.travis

before_install:
  - echo $TRAVIS_BUILD_DIR

  # Download Senhca CMD
  - wget http://cdn.sencha.com/cmd/6.5.0/no-jre/SenchaCmd-6.5.0-linux-amd64.sh.zip
  # Install Sencha CMD
  - "unzip -q SenchaCmd-6.5.0-linux-amd64.sh.zip -d SenchaCmd"
  - "cd SenchaCmd"
  - "mv *.sh SenchaCmd.sh"
  - "chmod +x SenchaCmd.sh"
  - "./SenchaCmd.sh -q"
  - "export PATH=~/bin/Sencha/Cmd/6.5.0.180/:$PATH"
  # - "sencha"
  - "cd .."

  # Build Sencha Apps
  - cd frontend/target
  - sencha app build production



  # Config GitHub
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git status
  - cd ../../
  - git add frontend/build/ -A
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"

# command to install dependencies
install:
  - pip install -r api/requirements.txt
  - pip install -r api/requirements_dev.txt
  - pip install coverage
  - pip install coveralls
  - pip install pep8

  # # Install Sencha CMD
  # - "unzip -q SenchaCmd-6.5.0-linux-amd64.sh.zip -d SenchaCmd"
  # - "cd SenchaCmd"
  # - "mv *.sh SenchaCmd.sh"
  # - "chmod +x SenchaCmd.sh"
  # - "./SenchaCmd.sh -q"
  # - "sencha"
  # - "cd .."

#before_script:
#  - "pep8 --exclude=migrations --ignore=E501,E225 src"
#   - pyflakes -x W src

# command to run tests
script:
  - cd api

  # Run pep8 on all .py files in all subfolders
#  - num_errors_before=`find . -name \*.py -exec pep8 --ignore=E402 {} + | wc -l`
  - num_errors_before=`find . -name \*.py -exec pep8 --exclude=migrations {} + | wc -l`
  - echo PEP8 Errors [$num_errors_before]

  # Create a Local Vars settings to prevent import errors.
  - cp dri/settings/travis.py dri/settings/local_vars.py

  # Run Tests and generate reports on coveralls
  - coverage run --source=. --omit='*migrations' manage.py test --verbosity=2
  - coveralls

  # Build Sencha Apps
  # - cd ../frontend/target
  # - sencha app build production
